// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdE71BybVZpw5xE8QV8W1LYlYpx2iS9lk',
    appId: '1:877978846301:web:e13b1ad189984e1a1279b4',
    messagingSenderId: '877978846301',
    projectId: 'personeltakip-8fced',
    authDomain: 'personeltakip-8fced.firebaseapp.com',
    storageBucket: 'personeltakip-8fced.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8egPTQyzZT_bKe_ZLd4BFv7Cm5LJkcM',
    appId: '1:877978846301:android:ffc045dd1cee2c171279b4',
    messagingSenderId: '877978846301',
    projectId: 'personeltakip-8fced',
    storageBucket: 'personeltakip-8fced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOdW0Xx0hX7nAzvRVjyofBSL9ipRosvQ',
    appId: '1:877978846301:ios:90ea9bcb6d39def91279b4',
    messagingSenderId: '877978846301',
    projectId: 'personeltakip-8fced',
    storageBucket: 'personeltakip-8fced.firebasestorage.app',
    iosBundleId: 'com.example.personelTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOdW0Xx0hX7nAzvRVjyofBSL9ipRosvQ',
    appId: '1:877978846301:ios:90ea9bcb6d39def91279b4',
    messagingSenderId: '877978846301',
    projectId: 'personeltakip-8fced',
    storageBucket: 'personeltakip-8fced.firebasestorage.app',
    iosBundleId: 'com.example.personelTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdE71BybVZpw5xE8QV8W1LYlYpx2iS9lk',
    appId: '1:877978846301:web:f68fa3f880d393471279b4',
    messagingSenderId: '877978846301',
    projectId: 'personeltakip-8fced',
    authDomain: 'personeltakip-8fced.firebaseapp.com',
    storageBucket: 'personeltakip-8fced.firebasestorage.app',
  );
}
